TopCategory.create(cat_name: '資産')
TopCategory.create(cat_name: '負債')
TopCategory.create(cat_name: '純資産')
TopCategory.create(cat_name: '収益')
TopCategory.create(cat_name: '費用')

SubCategory.create(top_category_id: 1, cat_name: '当座資産', asset_val: 1)
SubCategory.create(top_category_id: 1, cat_name: '棚卸資産', asset_val: 1)
SubCategory.create(top_category_id: 1, cat_name: 'その他流動資産', asset_val: 1)
SubCategory.create(top_category_id: 1, cat_name: '有形固定資産', asset_val: 2)
SubCategory.create(top_category_id: 1, cat_name: '無形固定資産', asset_val: 2)
SubCategory.create(top_category_id: 1, cat_name: '投資その他の資産', asset_val: 2)
SubCategory.create(top_category_id: 1, cat_name: '繰延資産')
SubCategory.create(top_category_id: 2, cat_name: '流動負債')
SubCategory.create(top_category_id: 2, cat_name: '固定負債')
SubCategory.create(top_category_id: 3, cat_name: '資本金')
SubCategory.create(top_category_id: 3, cat_name: '資本剰余金')
SubCategory.create(top_category_id: 3, cat_name: '利益剰余金')
SubCategory.create(top_category_id: 4, cat_name: '売上高')
SubCategory.create(top_category_id: 4, cat_name: '営業外収益')
SubCategory.create(top_category_id: 4, cat_name: '特別利益')
SubCategory.create(top_category_id: 5, cat_name: '売上原価')
SubCategory.create(top_category_id: 5, cat_name: '販売費および一般管理費')
SubCategory.create(top_category_id: 5, cat_name: '営業外費用')
SubCategory.create(top_category_id: 5, cat_name: '特別損失')

CfCategory.create(cat_name: '現預金')
CfCategory.create(cat_name: '営業')
CfCategory.create(cat_name: '投資')
CfCategory.create(cat_name: '財務')
