TopCategory.create(cat_name: '資産')
TopCategory.create(cat_name: '負債')
TopCategory.create(cat_name: '純資産')
TopCategory.create(cat_name: '収益')
TopCategory.create(cat_name: '費用')

SubCategory.create(top_category_id: 1, cat_name: '当座資産', asset_val: 1)
SubCategory.create(top_category_id: 1, cat_name: '棚卸資産', asset_val: 1)
SubCategory.create(top_category_id: 1, cat_name: 'その他流動資産', asset_val: 1)
SubCategory.create(top_category_id: 1, cat_name: '有形固定資産', asset_val: 2)
SubCategory.create(top_category_id: 1, cat_name: '無形固定資産', asset_val: 2)
SubCategory.create(top_category_id: 1, cat_name: '投資その他の資産', asset_val: 2)
SubCategory.create(top_category_id: 1, cat_name: '繰延資産')
SubCategory.create(top_category_id: 2, cat_name: '流動負債')
SubCategory.create(top_category_id: 2, cat_name: '固定負債')
SubCategory.create(top_category_id: 3, cat_name: '資本金')
SubCategory.create(top_category_id: 3, cat_name: '資本剰余金')
SubCategory.create(top_category_id: 3, cat_name: '利益剰余金')
SubCategory.create(top_category_id: 4, cat_name: '売上高')
SubCategory.create(top_category_id: 4, cat_name: '営業外収益')
SubCategory.create(top_category_id: 4, cat_name: '特別利益')
SubCategory.create(top_category_id: 5, cat_name: '売上原価')
SubCategory.create(top_category_id: 5, cat_name: '販売費及び一般管理費')
SubCategory.create(top_category_id: 5, cat_name: '営業外費用')
SubCategory.create(top_category_id: 5, cat_name: '特別費用')

CfCategory.create(cat_name: '現預金')
CfCategory.create(cat_name: '営業')
CfCategory.create(cat_name: '投資')
CfCategory.create(cat_name: '財務')

Category.create(top_category_id: 1, sub_category_id: 1,  cf_category_id: 1, uuid: 1101, name: '現金')
Category.create(top_category_id: 1, sub_category_id: 1,  cf_category_id: 1, uuid: 1102, name: '当座預金')
Category.create(top_category_id: 1, sub_category_id: 2,  cf_category_id: 2, uuid: 1201, name: '繰越商品')
Category.create(top_category_id: 1, sub_category_id: 3,  cf_category_id: 2, uuid: 1301, name: '前払費用')
Category.create(top_category_id: 1, sub_category_id: 4,  cf_category_id: 3, uuid: 1401, name: '電子機器')
Category.create(top_category_id: 1, sub_category_id: 4,  cf_category_id: 3, uuid: 1412, name: '予算減価償却累計額')
Category.create(top_category_id: 1, sub_category_id: 5,  cf_category_id: 3, uuid: 1501, name: 'ソフトウェア')
Category.create(top_category_id: 1, sub_category_id: 6,  cf_category_id: 3, uuid: 1601, name: 'SBI預金')
Category.create(top_category_id: 2, sub_category_id: 8,  cf_category_id: 2, uuid: 2101, name: '買掛金')
Category.create(top_category_id: 2, sub_category_id: 8,  cf_category_id: 2, uuid: 2106, name: 'VISAカード')
Category.create(top_category_id: 2, sub_category_id: 9,  cf_category_id: 3, uuid: 2201, name: '設備未払金')
Category.create(top_category_id: 3, sub_category_id: 10, cf_category_id: 4, uuid: 3101, name: '資本金')
Category.create(top_category_id: 3, sub_category_id: 11, cf_category_id: 4, uuid: 3201, name: '資本準備金')
Category.create(top_category_id: 3, sub_category_id: 12, cf_category_id: 4, uuid: 3303, name: '繰越利益剰余金')
Category.create(top_category_id: 4, sub_category_id: 13, cf_category_id: 2, uuid: 4101, name: '商品売上')
Category.create(top_category_id: 4, sub_category_id: 13, cf_category_id: 2, uuid: 4102, name: '給与収入')
Category.create(top_category_id: 4, sub_category_id: 14, cf_category_id: 2, uuid: 4201, name: '受取利息')
Category.create(top_category_id: 4, sub_category_id: 15, cf_category_id: 3, uuid: 4301, name: '還付金')
Category.create(top_category_id: 5, sub_category_id: 16, cf_category_id: 2, uuid: 5101, name: '仕入')
Category.create(top_category_id: 5, sub_category_id: 16, cf_category_id: 2, uuid: 5102, name: '食費')
Category.create(top_category_id: 5, sub_category_id: 17, cf_category_id: 2, uuid: 5201, name: '発送費')
Category.create(top_category_id: 5, sub_category_id: 17, cf_category_id: 3, uuid: 5209, name: '予算減価償却費')
Category.create(top_category_id: 5, sub_category_id: 17, cf_category_id: 2, uuid: 5210, name: '支払家賃')
Category.create(top_category_id: 5, sub_category_id: 18, cf_category_id: 3, uuid: 5301, name: '娯楽費')
Category.create(top_category_id: 5, sub_category_id: 19, cf_category_id: 3, uuid: 5405, name: '手術費')
